### ISSUE TITLE
Can't generate video file

### ISSUE THREAD

**Issue by patatman** [KKarmugil/scrape-reddit-video-maker#1]
I've tried to run the program, and everything seems to be working except the `videoz` function.
I'm getting an error: 
```python
videoz() takes 0 positional arguments but 1 was given
  File "/Users/pjeursen/projects/scrape-reddit-video-maker/main.py", line 239, in main
    videoz(i)
  File "/Users/pjeursen/projects/scrape-reddit-video-maker/main.py", line 243, in <module>
    main()
```
Look to be in:
```python
    for i in range(0,numberOfPost):
        try:
            videoz(i)
        except:
            print("ERROR "+str(i))
```

**Comment by KKarmugil** [comment]
OK I will check it out and let you know

its not videoz(i) it shoud be allaudio(i)

**Comment by KKarmugil** [comment]
for i in range(0,numberOfPost):
        try:
            allaudio(i)
        except:
            print("ERROR "+str(i))

**Comment by patatman** [comment]
It was a different issue, that the code expects a Windows host machine.
I'm running OSX.

The Path is different for both operating systems.

```
path=path.capitalize()
#path=(path.replace('\\', '\\\\'))
path=(path+"/")
print (path)
```

**Comment by KKarmugil** [comment]
I don't have mac can you fix this for me

**Comment by KKarmugil** [comment]
I fixed it check it out
